In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[276, 8625, 9430, 8130],
 [276, 8625, 9430, 105],
 [276, 592, 9430, 2924],
 [8067, 8046, 2486, 9810, 3677],
 [8067, 8046, 2486, 9810, 1104],
 [8822, 276, 8351, 9430, 9229],
 [6306, 5783, 8038, 9810]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  276 8625 9430 8130]
 [   0    0    0    0  276 8625 9430  105]
 [   0    0    0    0  276  592 9430 2924]
 [   0    0    0 8067 8046 2486 9810 3677]
 [   0    0    0 8067 8046 2486 9810 1104]
 [   0    0    0 8822  276 8351 9430 9229]
 [   0    0    0    0 6306 5783 8038 9810]]


In [51]:
## feature representation
dim=10

In [58]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length)) 

In [59]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[[-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02149255,  0.01142528, -0.04848034,  0.01471195,
          0.04152788,  0.02507514,  0.04133644, -0.02805283,
         -0.00418174,  0.04770139],
        [-0.03876619,  0.01627511, -0.01133721, -0.00446368,
          0.04551095, -0.01271309,  0.00759164, -0.02567892,
          0.02940546,  0.04718573],
        [ 0.01429572, -0.01878803, -0.00065681,  0.0

In [55]:
embedded_docs[0]

array([   0,    0,    0,    0,  276, 8625, 9430, 8130])

In [56]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


array([[[-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02174555, -0.03052121, -0.00390782, -0.01221853,
         -0.03477424, -0.04961811, -0.04657147,  0.03273876,
         -0.01704969, -0.01666534],
        [-0.02149255,  0.01142528, -0.04848034,  0.01471195,
          0.04152788,  0.02507514,  0.04133644, -0.02805283,
         -0.00418174,  0.04770139],
        [-0.03876619,  0.01627511, -0.01133721, -0.00446368,
          0.04551095, -0.01271309,  0.00759164, -0.02567892,
          0.02940546,  0.04718573],
        [ 0.01429572, -0.01878803, -0.00065681,  0.0